### ISSUE TITLE
Add scope to services

### ISSUE THREAD

**Issue by marcusdroy** [boomerang-io/roadmap#11]
## Add

Add WorkflowEntity property scope

Valid values are:
- system
- team

Workflows that are created with a team scope require the flowTeamId to be supplied.

Create new workflow team listing end point

- /workflow/systemflows, return list of only system scope workflows
- Update /internal/workflows to return the workflow scope

Developer notes

- Only platform admins and operators are able to see and update system workflows
- Quotas do not apply to system workflows

Discussion points

- UI Currently has team in the url (flow/apps/flow/teams/5eeb835caea46a0d82384d76/editor/5f35911f5f4af3491d51ff74/workflow), system workflows do not have a team.

**Comment by tlawrie** [comment]
Based on discussion, a decision has been made to use an attribute on the workflow creation endpoint for `?scope=system`

We need to make sure
- that it checks can the user create a system scoped workflow
- that it defaults to team if attribute not provided
- no team is required if system scoped

Additionally need to discuss if we are using an attribute to retrieve system workflows or is that a separate endpoint...

**Comment by tlawrie** [comment]
After discussion with @BenjaminRuby the execution of a system scoped workflow, would need to _optionally_ know which team requested the execution.

An example would be in embedded mode where the Flow teams are really CICD teams, and therefore the Flow team would be executing the Workflow (that is system scoped) this will allow a team to appear in Activity.

However, System workflows could still be triggered by the system and therefore have no team so we need to cater for no team in the Activity Screen.
