### ISSUE TITLE
Slack us feedback link closed

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#116]
**Describe the bug**
The current linked used in the Slack us Feedback in the banner on the workflows page is now inactive

**To Reproduce**
Steps to reproduce the behavior. Think about:

- Navigate to Workflows
- Have the banner expanded
- Click on Slack us Feedback

**Expected behavior**
Be taken to the flow channel in Slack or ask to join

**Additional context**
    "from": "https://join.slack.com/t/boomerang-io/shared_invite/zt-f1j2szfp-90s6mAud11PxoIKeKCr2og",
    "to": "https://join.slack.com/t/boomerang-io/shared_invite/zt-pxo2yw2o-c3~6YvWkKNrKIwhIBAKhaw",

**Comment by BenjaminRuby** [comment]
Hey @tlawrie - @Okisa pointed out that the new slack join link also appears to no longer be active

**Comment by tlawrie** [comment]
Interesting. I have it set to never expire and I copied the link again and it still is using `https://join.slack.com/t/boomerang-io/shared_invite/zt-pxo2yw2o-c3~6YvWkKNrKIwhIBAKhaw`

**Comment by tlawrie** [comment]
@Okisa what do you get when you try that link?

**Comment by Okisa** [comment]
@tlawrie Now the links are working, I'll update the app to use it.

**Comment by Okisa** [comment]
@BenjaminRuby PR Opened here: https://github.com/boomerang-io/flow.client.web/pull/48
