### ISSUE TITLE
Task Alignment with Industry & Tekton Phase 2

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#118]
## Description
Following on from boomerang-io/roadmap#60 we are moving to adopt not only the Tekton Task model but the Tekton Task implementation in replacement to Kubernetes Jobs

## Impacts
- the controller execution
- changes to controller endpoints with removal of `/controller/results`
- the integration between the controller and the workflow service
  - updates to the Task model as part of Execute Task
    - new `results` list with name and description in an object
    - new 'script' element
    - removal of the `lifecycle` as part of `configuration`
    - new env variables section
- the allowed inputs in task manager on the UI
  - update basic details
     - remove the enableLifecycle watcher toggle
     - add in the script multiline block
     - add in an ability to define environment variables
  - new result parameters definition section
     - ability to define a name and description for result parameters 

## Timeline
Implemented as part of release 3.3 however this depends on Tekton 0.24 due to the need for Host Alias support

## Open Questions
- Do we let Tekton take care of the parameter replacement or do we do it as part of resolving our version of the task template
- How do we allow defining environment variables
- How do we do allow defining results.

## Acceptance criteria and scope
Define what is a must-have for launch and in-scope. 

| Feature | Given | When | Then |
| --- | --- | --- | --- |
| | | |

**Comment by tlawrie** [comment]
@tlawrie to add in Environment variables to the Task model

**Comment by BenjaminRuby** [comment]
@marcusdroy @tlawrie is `script` a required/optional attribute of a task?

**Comment by marcusdroy** [comment]
@BenjaminRuby it would be optional

**Comment by tlawrie** [comment]
Yes. Optional.
