### ISSUE TITLE
Importing Workflow doesn't pull in name or description

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#127]
**Describe the bug**
The import workflow modal should automatically populate name and description to be changed by the user as needed.

**To Reproduce**
Steps to reproduce the behavior. Think about:

- Navigate to Workflows
- Create new workflow
- Toggle to import
- Pick a workflow JSON

**Expected behavior**
Fields are pre-populated

**Comment by Okisa** [comment]
Opened a PR with a fix for this issue:
https://github.com/boomerang-io/flow.client.web/pull/60
