### ISSUE TITLE
Task Select Parameters Default Option not saving

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#129]
**Describe the bug**
The default option for Select type parameters are not saving

**To Reproduce**
Steps to reproduce the behavior. 

- Go to Manage Tasks
- Choose a task
- Create a Select type parameter with options and select a default
- Hit save
- Open parameter. No default option saved.

**Expected behavior**
Default option to be saved

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f96002d49baed1deae1cb62/40fe287e-5efb-414c-889d-6dd408ec7206)

**Additional context**
Need to check the YAML editor to, this should be saving in defaultValue.

**Comment by BenjaminRuby** [comment]
@Okisa can you please also confirm that this works within the Admin task manager as well

**Comment by Okisa** [comment]
@tlawrie  @BenjaminRuby  Opened a PR for this fix: https://github.com/boomerang-io/flow.client.web/pull/44
