### ISSUE TITLE
Handle result parameters for Tasks with unknown or dynamic results

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#135]
With the move to Tekton Task Results needing to be defined rather than be dynamic we need to understand how to do this for the tasks that don't have predefined result parameters such as:
- script
- custom tasks
- JSON to result parameter

Possible solutions are;
1. Add a result parameter creatable to the Script and Custom task types
2. Figure out how to include the dynamic result parameter creation as a side car (implement lifecycle sidecar as a feature enhancement of Boomerang Flow over and above Tekton)

**Comment by tlawrie** [comment]
After much investigation, it would become highly complex trying to run the original lifecycle watcher system in the implementation of Tekton. In particular as running as a sidecar, it will be terminated as soon as the main step containers are finished, not giving time to read the files from the container and post back. Alternatively, running the lifecycle as a final step means that it wont always run due to follow on sequential steps only running after prior success.

Linked Issues / TEPs:
- https://github.com/tektoncd/pipeline/issues/4012
- https://github.com/tektoncd/community/blob/main/teps/0040-ignore-step-errors.md

The solution here is now to implement the following
1. Update Task: "Json Path to Result Parameter" to handle retrieving from file.
2. Update the "Execute Shell" task to define result parameters
3. Update the "Run Custom Task" task to define result parameter

For (2) and (3) above we need to determine best implementation, most likely will be to create a tab on the modal for defining result parameters and utilize a similar implementation to Task Manager. Defining name and description for the result parameters.

**Comment by tlawrie** [comment]
To handle whether to show the parameter block is custom and script type.

This means migrating the shell and python tasks to be a script type in the collection.

**Comment by marcusdroy** [comment]
Services have been up pushed up to dev to include spots for saving output properties on a task configuration
"outputs" : [
        {
            "name" : "test here",
            "description" : "description here"
        }
    ]

Also new flow task template type "script" has been introduced so "script" and "custom" will be the tasks which we will display output properties.
