### ISSUE TITLE
Update Helm chart with appropriate feature falgs

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#14]
## Change
- Existing feature flags may need to be altered such as eventing

## Add
- New feature flags appropriate based on list

**Comment by BenjaminRuby** [comment]
- Manually Run Workflows
- App Activation
- Quotas
- Triggers
- Tokens?
- Insights
- Team Properties
- Global Properties
- Settings
- Task Manager
- Team Management
- User Management

@tlawrie @timrbula here is the feature flag list I had after going through the flow UI - anything else to add?

**Comment by tlawrie** [comment]
@BenjaminRuby does Manually Run Workflows match disabled / enabling triggers?

Other than that, I think the flags make sense.

**Comment by BenjaminRuby** [comment]
@tlawrie well if manually running workflows is not enabled - would we still want users to be able to potentially set up webhook / custom event?

**Comment by tlawrie** [comment]
@BenjaminRuby i think for now we just make it all triggers are disabled and we can sort out more detail as we iterate?

@amhudson I have added the following flags to the properties that go to the workflow service. Can you make sure something is returned in the feature endpoint for @BenjaminRuby to utilize in the UI?

All of the Flags are booleans

```
    flow.feature.workflow.quotas=
    flow.feature.workflow.triggers=
    flow.feature.workflow.tokens=
    flow.feature.team.properties=
    flow.feature.global.properties=
    flow.feature.team.management=
    flow.feature.user.management=
    flow.feature.taskManager=
    flow.feature.settings=
```

Additionally there is the `boomerang.activation` flag which should determine if the OTC is needing to be utilized.
