### ISSUE TITLE
Create a Task description incorrect

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#142]
**Describe the bug**
The create task description states that "All fields are required" however a number of the fields are marked as optional. so this does not make sense.

Additionally we need to determine if it makes sense to ask for more than just name and description and icon in this view or ask for all basic details

**To Reproduce**

- Navigate to Manage > Team Tasks
- Add a new task

**Expected behavior**
Would expect the description and required values to be in sync.

**Comment by Okisa** [comment]
@tlawrie For those values that are considered required currently just the `arguments` (actually I don't know how we use them) seems that could be optional?

**Comment by tlawrie** [comment]
Hi @Okisa so I dont think arguments are required either.

The updates are
1. Remove "All fields are required" from the description text at the top of the Add a new task modal.
2. Make arguments not required (we might have to validate that this is what the services are expecting)
3. Move Image above Arguments in the order
4. Add to the image info text. "Path to container image. If not specified, will use the systems default."
![image](https://user-images.githubusercontent.com/16438811/120059796-087df800-c097-11eb-90b1-906320d5c63c.png)
