### ISSUE TITLE
Improve the Workflow Editor Configure Labels Section

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#148]
## Change

- Currently, we state 'Custom Kubernetes Labels' which is accurate however as we focus on the non technical user experience, the end user won't necessarily know what Kubernetes is.
  - We need to adjust this to state 'Custom Labels'
  - We need to change the description to "Create custom labels that will be used at execution time and can be useful in debugging the workflow in Kubernetes"

## Additional Detail
@Okisa @LucasGrimauth can either of you take on this task. Let me know if there are any questions or suggest improvements? i am really just trying to alter the text to make it more non technical user friendly.

**Comment by Okisa** [comment]
@tlawrie @BenjaminRuby I will update the text to match the new description. I was also thinking to add an external link to the Kubernetes labels docs for more details, if you guys agree with this. A link like "For more details, check Kubernetes Docs" for https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

**Comment by tlawrie** [comment]
Hi @Okisa i like what you are thinking but not sure we want to push them towards kubernetes documentation for business users. Especially as there is another task in the backlog about expanding access to labels across the Flow UIs i.e. able to filter on labels in Workflows and Activity and Insights.

We could put a link to our documentation on Labels... which I'm not sure we have but you could write :D

**Comment by Okisa** [comment]
Hi @tlawrie 
Is this the current Docs for Labels? https://servicesessentials.ibm.com/docs/boomerang-cicd/8.1.0/how-to-admin/configuring-team-parameters

**Comment by tlawrie** [comment]
Hey @Okisa the Flow documentation is actually external. https://www.useboomerang.io/docs/boomerang-flow/3.2.0/introduction/overview

We would need to create some documentation about Labels somewhere probably under the Workflow Editor and then go from there.

**Comment by Okisa** [comment]
@tlawrie @BenjaminRuby Tried to write a bit for Custom Labels, would like some review on this.
PRs opened:
Flow Docs: https://github.com/boomerang-io/useboomerang.io/pull/10
Flow: https://github.com/boomerang-io/flow.client.web/pull/49

**Comment by tlawrie** [comment]
@Okisa really good work running with this. 

I have approved and merged in the documentation. I have also rebased the `flow-release-3.3` branch with this content.

For the web app, one small change needed from my side.
