### ISSUE TITLE
Flow Header not displaying custom app name

### ISSUE THREAD

**Issue by BenjaminRuby** [boomerang-io/roadmap#155]
**To Reproduce**
Navigate to flow via the lefthand menu in CICD.

**Screenshots**
![image (23).png](https://images.zenhubusercontent.com/5f997c3d144cc0adc7d23276/fdefdaaf-8fc1-4c55-bff5-00839c201c56)![image (22).png](https://images.zenhubusercontent.com/5f997c3d144cc0adc7d23276/12f7ea15-bb6b-490e-9c79-da881a44f0f1)

**Comment by BenjaminRuby** [comment]
@tlawrie @marcusdroy discussed in slack but bringing back to here. 

Do we have a flag to tell flow whether it's in cicd mode? So we can conditionally render the appName in the header.

**Comment by tlawrie** [comment]
Based on discussion and review of the issue, the following is the updated enhancement

**Requirements**
1. Implement a new toggle in Flow Settings for "Display Boomerang logo" OR ability to upload a new Logo
2. Implement a new input text box in Flow Settings for "Instance Name" which adjusts what's displayed in green.

**Solution**
Once the above is implemented, CICD can then override the settings in the loader to replace the default FLOW with CICD OR we can manually set it for now when installed with CICD.

**Comment by LucasGrimauth** [comment]
@tlawrie  hey Tyson, so the Flow Settings is just like the Admin and CICD Settings. It isn't hardcoded on the UI. The settings displayed on Flow comes from the `GET /workflow/settings/` endpoint.
Also, I am checking on dev now and I see the flow app name in the header here:
https://ocp2.cloud.boomerangplatform.net/dev/cicd/apps/flow/workflows

**Comment by tlawrie** [comment]
Thanks for that @LucasGrimauth 

@marcusdroy @amhudson so far adding dynamic name to Flow Settings, what steps do we need to take?

**Comment by timrbula** [comment]
@timrbula finally to review this again

**Comment by tlawrie** [comment]
Hey @timrbula can you let me know what setting is needed to be added to the Settings and then made it through to the Header for the custom name? or an uploaded logo?

I know its meant to be in the header / navigation of the web app but that references an import that I think is closed source.

**Comment by tlawrie** [comment]
Hey @timrbula updates have been made to send

```json
{ 
  "platform": {
     "appName": "Flow",
     "platformName": "Great Platform",
     "displayLogo": false,
     "logoURL": ""
  }
}
```

However, if we wanted to simplify the above payload, we could use the following


```json
{ 
  "platform": {
     "aname": "Great Platform Flow",
     "displayLogo": false,
     "logoURL": ""
  }
}
```

The only logic difference would be that 
- The default would be the Boomerang logo + Flow text
- the end administrators couldn't customize to have a Logo and Text, it would be logo or text
