### ISSUE TITLE
Update Available Parameters endpt after Saving a Task Configuration

### ISSUE THREAD

**Issue by BenjaminRuby** [boomerang-io/roadmap#176]
We currently pull in the available-parameters endpoint at the Editor component. The issue now is that we want to pull in new parameters as tasks are configured (so the results could be used in a subsequent task)

POST /{workFlowId}/available-parameters with the body of the revision -> will echo back the updated available parameters.

So what needs to be done: We can try to use this endpoint when saving a config to update the cache for available parameters.

**Comment by Okisa** [comment]
Opened a PR for this: https://github.com/boomerang-io/flow.client.web/pull/61
