### ISSUE TITLE
Fix argument and command representation

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#185]
**Describe the bug**

1. Arguments is space-delimited in the Task Template but NewLine delimited in the Run Custom Task
2. Command is treated as a literal string instead of newline (or space) delimited commands in an array
3. Arguments are also not optional. There are times when you want to create a task without arguments

**Expected behavior**

- A consistent experience across Task Templates, Team Task Templates, and Run Custom Task
- Use a multiline text area with newline delimited entries.
- Arguments are optional

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f96002d49baed1deae1cb62/e8ac833b-6d04-4fa3-b296-b36c86ad5c9f)
![image.png](https://images.zenhubusercontent.com/5f96002d49baed1deae1cb62/9171b83c-7146-46ba-9c4b-794fe6de0c72)

**Comment by tlawrie** [comment]
Controller adjusted to accept List<String> for command on branch `feat-185-fixcommand`

**Comment by Okisa** [comment]
Opened a PR for the UI: https://github.com/boomerang-io/flow.client.web/pull/70

**Comment by tlawrie** [comment]
Hey @Okisa could you make one slight adjustment. Can you change the order of whats shown in the task-template to be;

**Leave as is**
- Name
- Category
- Icon
- Description
then,
**Adjust**
- Image
- Command
- Arguments
- Script
- Working Directory
- Env

And also update the helper / description text for Command to
> Overrides the entry point of the container. Delimited by a new line.
