### ISSUE TITLE
Fix view users and create team

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#186]
**Describe the bug**
In Standalone mode, create team and create user don't work. 

**Expected behavior**
Ability to create a team and create users

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f96002d49baed1deae1cb62/603fce8a-7dd3-44fd-b08e-40f3bcf460e7)
![image.png](https://images.zenhubusercontent.com/5f96002d49baed1deae1cb62/8289f438-3f3b-4993-abfe-a60d70babc3d)

**Comment by dlandry318** [comment]
https://github.com/boomerang-io/flow.service.workflow/pull/93
