### ISSUE TITLE
Clean up the documentation

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#218]
## Change

- The biggest overhaul of the documentation since release 2.x

**Comment by tlawrie** [comment]
Preview: https://deploy-preview-30--useboomerangio.netlify.app/docs/boomerang-flow/3.4.0/introduction/overview

Still to do

- [ ] How To Manage section
- [ ] How to Guide section
- [ ] Update Task architecture with the settings related to Tasks and more detail as to the integration or opinionated choices
- [ ] Update installing section, particular the post install with a link to Settings with them all defined.

**Comment by morarucostel** [comment]
To document from 3.4.0, 3.4.1 and 3.5.0: 
 - templates, 
 - system workflows, 
 - my workflows vs team's workflows
 - fix to the schedule trigger, 
 - NATs, Tekton version changed.
 
 @morarucostel please create a branch with 3.5.0 at least with the release notes and whatever we can do until the end-date.

**Comment by tlawrie** [comment]
Documentation has been updated with structural modifications ready for Flow 3.6.0
