### ISSUE TITLE
After activation you are left on a blank screen

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#222]
**Describe the bug**
On first install after entering the activation code, you are left on a blank screen and have to refresh the page to be redirected to the workflows

**To Reproduce**
Steps to reproduce the behavior. Think about:

1. Install Flow into a fresh DB
2. Navigate to flow
3. Enter the activation code

**Expected behavior**
Automatically redirected to My Workflows

**Additional context**
Chrome. Using 3.4 Release Candidate.

**Comment by tlawrie** [comment]
Hey @BenjaminRuby did you make any progress on this since the Community call?

**Comment by timrbula** [comment]
@timrbula @morarucostel to work together to fix this

**Comment by timrbula** [comment]
@timrbula to try again

**Comment by timrbula** [comment]
@morarucostel Can you try with the 3.9.0 build of flow.client.web?
