### ISSUE TITLE
Workflow service attempts to connect to NATS

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#223]
**Describe the bug**
When the workflow service starts up it trys to connect to NATS Jetstream and does not respect the `eventing.jetstream.enabled` flag.

**To Reproduce**
Steps to reproduce the behavior. Think about:

- Navigate to the Workflow service in Kubernetes
- View the logs on start up (and later after reconnection timeout)

**Expected behavior**
The service to respect the flag and not try to connect to NATS Jetstream.

**Additional context**
Tag: 3.1.44

**Potential Fix**
In either the `JetstreamListener.java` in Workflow service or in the [Lib Stream](https://github.com/boomerang-io/flow.lib.streaming/blob/main/src/main/java/io/boomerang/jetstream/ConnectionAutoConfiguration.java)

**Comment by corcoja** [comment]
Fixed in `lib.eventing` version 0.2.0 (https://github.com/boomerang-io/lib.eventing/releases/tag/0.2.0).
