### ISSUE TITLE
User API should default to "user" not "admin" as well as other issues

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#231]
**Describe the bug**
The current Users API in the Swagger documentation shows the user type as "admin". This should not be the default user type. Also is there a way to document the options so people know there are different types or should this be handled outside of the Swagger and inside the [Docs](https://www.useboomerang.io/docs/boomerang-flow/3.4.0/architecture/ap-is)

**To Reproduce**

- Navigate to the swagger Ui and look the at the payload for create user (as well as the others I imagine)

**Expected behavior**
Defaults to "user" and also documents the options

**Comment by tlawrie** [comment]
Additionally the User object has a Flow Teams and a Teams section. Are both needed?

**Comment by tlawrie** [comment]
It also allows me to create a user with an id of "string". Should this not be overwritten by the MongoDB _id?

**Comment by amhudson** [comment]
fixed with 3.1.54
