### ISSUE TITLE
Parameters not allowed in URL input type

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#238]
**Describe the bug**
Enterting a parameter in the format of `$(tasks.Get Team ID.results.evaluation)` as part of the URL is not allowed.

We would like to validate if the input is a valid URL. But we also want to allow the input to be valid if it is a parameter (i.e. if the input uses our parameter syntax)

**To Reproduce**
Steps to reproduce the behavior. Think about:

1. Open a Execute HTTP Call task
2. Attempt to use a parameter in the URL input

**Expected behavior**
It accepts the parameter.

**Comment by tlawrie** [comment]
Hey @LucasGrimauth did you make any progress on this since the Community call?

**Comment by Okisa** [comment]
@BenjaminRuby Also updated Flow to handle param syntax for Task Fields form and Workflow Editor Params 
https://github.com/boomerang-io/flow.client.web/pull/107

**Comment by tlawrie** [comment]
Resolved and verified
