### ISSUE TITLE
Workflow Service Mode Replacement

### ISSUE THREAD

**Issue by marcusdroy** [boomerang-io/roadmap#24]
## Change

Remove **flow.mode** enum FlowMode to instead use the following property values

- flow.externalUrl.user
- flow.externalUrl.team

**External User Profile**

If flow.externalUrl.user is blank, default to getting users in local user flow as if it was running in stand alone mode. Use this url to retrieve the user profile (in this case it was going to core to get the user profile.

Please see UserIdentityServiceImpl.java and TeamServiceImpl.java

**External User Profile**
If flow.externalUrl.team is blank, default to getting a users team inside the flow data store. If it not blank use the this url to retrieve the external teams.

Please see  TeamServiceImpl.java

`
List<FlowTeamEntity> flowTeam = null;
if (FlowMode.EMBEDDED.getMode().equals(flowMode)) {
     flowTeam = this.cicdService.getCICDTeams();
}`

**Comment by amhudson** [comment]
https://github.com/boomerang-io/flow.service.workflow/pull/37
