### ISSUE TITLE
Update Workflow Activity Advanced Detail with Tekton

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#240]
## Change

- The current Advanced Detail shows the kubectl commands but doesn't show the tkn detail. Need to update with something similar to `tkn tr list -n flowabl-live --label boomerang.io/workflow-id=61454e2d1000b141daa8f85f --label boomerang.io/workflow-activity-id=615ea461a1747c3cd93f4eb9`

Determine what message to show if they don't have the tkn CLI installed.

**Comment by tlawrie** [comment]
Its also missing namespace information. We should add a note about adding in the respective namespace

**Comment by timrbula** [comment]
@timrbula to update text
