### ISSUE TITLE
Task View Result Parameters not showing

### ISSUE THREAD

**Issue by BenjaminRuby** [boomerang-io/roadmap#243]
**Describe the bug**
Result Properties are not shown for a task in activity. UI Is trying to access `outputs` service is returning `results`

**Comment by tlawrie** [comment]
Hey @BenjaminRuby checking in on this one? have we made any progress?

**Comment by tlawrie** [comment]
In verifying this, it appears to not be implemented correctly. As you can see from the two screenshots, it shows the description as a value. And then just appends the value. To show the description it should show three columns. Name | Description | Value. If no description we put `-`

![image](https://user-images.githubusercontent.com/16438811/141887440-70f1bef7-ab7b-4695-8f25-bb04146c1d26.png)
![image](https://user-images.githubusercontent.com/16438811/141887447-563aa13e-e846-4a96-8a0d-dd8440d92bb2.png)

**Comment by Okisa** [comment]
Opened a new PR for the additional column
https://github.com/boomerang-io/flow.client.web/pull/108

**Comment by tlawrie** [comment]
Issues resolved and verified.
