### ISSUE TITLE
Fix team creation API

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#247]
**Describe the bug**
The team creation endpoint accepts a full model however only respects the team name and then you have to call subsequent API endpoints.

**To Reproduce**
- Call the create team API
- Pass in quotas or team members
- Only the team with the name gets created, no other information is respected

**Expected behavior**
However the User create endpoint allows you to set all the relevant information on create which is probably the design we want.

**Additional context**
https://github.com/boomerang-io/flow.service.workflow/pull/115

**Comment by tlawrie** [comment]
Hey @marcusdroy @amhudson what do you think?

**Comment by amhudson** [comment]
@tlawrie @marcusdroy I've made some additional updates to https://github.com/boomerang-io/flow.service.workflow/pull/115 to allow for adding users on team creation

**Comment by tlawrie** [comment]
hey @amhudson awesome. So with these latest commits, is everything covered?

**Comment by tlawrie** [comment]
Hey @amhudson one part didn't work.

I set `maxWorkflowExecutionMonthly` to `200` but it left it as the default `20`

**Comment by amhudson** [comment]
fixed with workflow 3.1.81
