### ISSUE TITLE
View User Details shows incorrect response

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#274]
### Describe the bug

When clicking on view user details in the user management page, it shows the id of the teams rather than whats expected which is the # of teams.

I propose, that whilst this is needing to be fixed, we instead also show the team names. something like

**Teams (3)**
- Team 1
- Team 2
- Team 3

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

Navigate to Administer > Users and select the ellipses on a user and click view details. This will open a modal that shows incorrect information. 

### Additional Contenxt

![image](https://user-images.githubusercontent.com/16438811/138615819-6e1d7195-e5bf-49ad-9063-682e726a6eff.png)

**Comment by tlawrie** [comment]
Ultimately I think there are a number of issues with the Users screen in standalone mode.

1. On first load of the page, the table shows all users (not paged). Not sure if front end or back end issue
2. The page gets stuck and doesn't scroll in chrome on first load
3. Created dates for users are showing incorrectly when the user is created via the API and there is no firstLoginDate in the model.
4. We should show Created Date (first login date) and also last login date
5. We should migrate this to a detailed user page not the modal.
6. Link to the User Detail page (once it has a URL) from the Teams Page and to the Teams Page from the Users.

**Comment by tlawrie** [comment]
Based on community meet up, additional service endpoints will be provided by @marcusdroy

**Comment by timrbula** [comment]
@BenjaminRuby @timrbula to review
