### ISSUE TITLE
Allow special characters in Team Name

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#275]
## Change

- Update Team Name to allow a list of special characters such as `'` however probably no need to support all special characters.

**Comment by tlawrie** [comment]
In looking at the code. I don't see any validation restricting this on the service side. @marcusdroy can you confirm?

**Comment by tlawrie** [comment]
Good question from @timrbula around what characters do we want to allow?

Any unicode character. Yay to emoji's 🐼

**Comment by tlawrie** [comment]
Add support to render emoji

**Comment by timrbula** [comment]
@timrbula to delete a line of code to support this
