### ISSUE TITLE
Upgrade Tekton to 0.27.2

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#277]
## Change

- Upgrade Tekton
- Upgrade Fabric8 client

**Comment by tlawrie** [comment]
@gchickma @marcusdroy We are currently on 24.1 of Tekton.

Looking at the release notes https://github.com/tektoncd/pipeline/releases there are some changes required.
- 0.25: I don't believe there is anything critical, particularly because we don't use PipelineRuns yet
- 0.26: I don't believe we will need to do anything for this release either
- 0.27: lots of changes. Most behind alpha flags. Most of this affects functionality we _would_ need when we move the entire workflow execution to a pipeline to have the same as our current functionality by using onError and whenExpressions to guard tasks. However that's slated for Flow 4.0
  - It also updates `knative.dev/pkg` which is a Tekton dependency but usually requires updates to Fabric8 that need regenerating, last time I had to do that for the community so not sure if its been done already.
  - 0.27.3 also brings in compatibility with Kubernetes 1.22
- 0.28: brings in lots of changes. 
  - Terminating pods so resource quotas are now able to be used properly. 
  - `.` notation back in scope for parameters. e.g `$(params["foo.bar"])`
  - Cached entrypoint digest (this was a fix to our issue)
  - Label changes

I suggest 
1. we upgrade to 0.26 and take the system for a few spins without updating anything in controller. It should still work with minimal to no issues.
2. we then upgrade to 0.27.2 and revalidate. (leaving 0.27.3 until we pick up 0.28) If too many issues arise we can fall back on 0.26
3. Create a future issue for a future release to look at 0.28+ (inclusive of 0.27.3)

Let me know your thoughts...

**Comment by tlawrie** [comment]
Upgrade to Tekton 0.26 as part of Helm Chart 4.11.1 and validated a simple workflow with no issues.

Further work to be done for updating to 0.27.2

**Comment by tlawrie** [comment]
Tekton 0.30.0 was just released. No impacts to functionality that we use.

**Comment by morarucostel** [comment]
Hey @tlawrie , release 3.5.0 should include only the upgrade to Tekton 0.26 or do you think we can go all the way to 0.27.2 ?

**Comment by tlawrie** [comment]
Upgrade to Tekton 0.27.2 in Helm Chart 4.11.3 and validated with a simple workflow.

Further verification testing is needed.

**Comment by morarucostel** [comment]
Hey @aiciobanu , do you think you can do a sanity check on the flow installation using Tekton 0.27.2 in one of your environments?
