### ISSUE TITLE
Remove the 'change schedule' on the Workflow > Configure page (shows up when enabling the schedule trigger) and add an action to add a schedule on the schedule tab. (TBA if we can take them to the schedule tab through a click)

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#281]

**Comment by timrbula** [comment]
@tlawrie Thinking that we can leave a link in there for 3.6 and remove in a later version. That will give users a smooth transition to using the Schedule tab if they don't notice it immediately / see the release notes/ etc.
