### ISSUE TITLE
Selected Team with wrong validation

### ISSUE THREAD

**Issue by Okisa** [boomerang-io/roadmap#284]
When importing a Team Workflow, the selected team shows a wrong error message:

![image](https://user-images.githubusercontent.com/26601959/140418407-a441ad6a-15dc-418e-9b7c-aea610834d92.png)

**Comment by Okisa** [comment]
Opened a PR for this issue here:
https://github.com/boomerang-io/flow.client.web/pull/100

**Comment by tlawrie** [comment]
Verified as part of 3.4.1
