### ISSUE TITLE
Migration for existing workflow schedule triggers

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#286]
## Change

- Find existing active schedule trigger and
  - Delete existing quartzjob
  - Create new schedule entity
  - Create new quartz job

**Comment by tlawrie** [comment]
@marcusdroy do we need to bother with this? and if so, how do we design this? I've not done loader changes before... but I think we could take whats under the `flow_workflows` triggers > scheduler elements and migrate them into a new `flow_workflows_schedules` object.

Is that something the loader can handle? the below pseudocode provides an example but does raise the question with what we do for parameters? do we take the defaults from the workflow? what happens if a required parameter has no value. 

```
List<WorkflowEntity> wfEntities = workflowRepository.getAllActiveWorkflows();
wfEntities.forEach(wf -> {
  TriggerSchedulers ts = wf.getTriggers().getScheduler();
  WorkflowSchedule schedule = new WorkflowSchedule();
  if (ts.getAdvancedCron == true) {
    schedule.setType(WorkflowScheduleType.advancedCron);
  } else {
    schedule.setType(WorkflowScheduleType.cron);
  }
  if (ts.getEnable == true) {
    schedule.setStatus(WorkflowScheduleStatus.active);
  } else {
    schedule.setStatus(WorkflowScheduleStatus.inactive);
  }
  schedule.setTimezone(ts.getTimezone);
  schedule.setCronSchedule(ts.getSchedule);
  workflowSchedulerService.createSchedule(wf.getId(), schedule);
}
```

![image](https://user-images.githubusercontent.com/16438811/146745351-710f1a65-dec8-4ef4-b119-dd7b1e39d37d.png)

**Comment by tlawrie** [comment]
Hi @amhudson @marcusdroy as mentioned this is the migration needed for the legacy schedule trigger. The above is quite detailed and I attempted to make the pseudo code.

The only unknown is the parameter values... they are now stored against the schedule... for this migration do we just copy the default value of the parameter?

**Comment by amhudson** [comment]
Migration for triggers https://github.com/boomerang-io/flow.loader/pull/60
