### ISSUE TITLE
Unable to update system workflows

### ISSUE THREAD

**Issue by amhudson** [boomerang-io/roadmap#292]
### Describe the bug

For POST /workflow/workflow//{workFlowId}/revision and POST /workflow/workflow/{workFlowId}/available-parameters, the UI is sending a payload similar to the following:

`
{
    "dag": {},
    "config": {
        "nodes": [
            {
                "inputs": {
                    "output": "",
                    "taskName": "",
                    "value": "",
                    "outputs": []
                },
                "nodeId": "",
                "taskId": "",
                "type": "",
                "taskVersion": 1,
                "outputs": []
            }
        ]
    },
    "changelog": {}
}`

where `outputs` array is nested within as well as on the same level as the `inputs` object. The proper payload should be similar to

`{
    "dag": {},
    "config": {
        "nodes": [
            {
                "inputs": {
                    "output": "",
                    "taskName": "",
                    "value": ""
                },
                "nodeId": "",
                "taskId": "",
                "type": "",
                "taskVersion": 1,
                "outputs": []
            }
        ]
    },
    "changelog": {}
}`
where `outputs` is only provided on the same level as `inputs`

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

1. Create a system workflow and save
2. Try to update and save a revision to the workflow, 400 Bad Request response recieved

**Comment by tlawrie** [comment]
Issues resolved and verified
