### ISSUE TITLE
No workflow templates by default in a Flow Installation

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#294]
### Describe the bug

There are currently no Flow Workflow Templates in the default installation of Flow

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

1. Navigate to the Workflows screen (either My or Team)
2. Click Add Template
3. Modal shows no templates

### Additional Contenxt

- [x] #295
- [ ] Github Bots
- [ ] maybe the on-boarding flows

**Comment by tlawrie** [comment]
Some sample workflow ideas
- GitHub Issue Cleanup Bot
- My First Automated Workflow
- Integrating with xxx (example of using and processing an API)
- Google Sheets example

**Comment by timrbula** [comment]
@morarucostel @gchickma Something to think on

**Comment by morarucostel** [comment]
Just created a sample workflow with:
`Sending the mongodb query results as an attachement of an email.`

**Comment by tlawrie** [comment]
hey @morarucostel were you able to figure out why these workflows couldn't be imported?

**Comment by morarucostel** [comment]
@tlawrie I can not reproduce the import failure on any Flow instances. 
I tried it myself and also asked other colleagues and they were able to import them without problems in both, `My workflows` and `Team workflows`.

Could you please have a look at the logs on your side?

**Comment by tlawrie** [comment]
Hi Costel,

This import issue was for the workflow template. So System Workflows >
Templates

**Comment by tlawrie** [comment]
Hi @morarucostel checking in on this. I know there were two templates you were looking at adding but the import functionality doesn't work on the System Workflows screen.

**Comment by tlawrie** [comment]
@morarucostel to re-attempt upload and then loader

**Comment by morarucostel** [comment]
hey @tlawrie , the import is working, I just didn't trigger the new build, so the code was not in the latest image. Now the code is in flow-service-workflow:3.4.62 and the import is working. 

<img width="1479" alt="Screenshot 2022-06-29 at 12 46 10" src="https://user-images.githubusercontent.com/13904499/176418660-632b5482-a3ed-4383-9590-985b3f2e696c.png">

**Comment by morarucostel** [comment]
Something strange is happening when you open an imported workflow, it shows no nodes in the workflow.
 
<img width="1571" alt="Screenshot 2022-06-29 at 12 47 38" src="https://user-images.githubusercontent.com/13904499/176418871-734bdfe0-d48f-4a71-8ece-2baf016ed570.png">

**Comment by tlawrie** [comment]
Created new issue to track additional workflow templates. These two workflow templates are now in the loader `0.5.7`
