### ISSUE TITLE
Add TLS support for MongoDB

### ISSUE THREAD

**Issue by gchickma** [boomerang-io/roadmap#296]

**Comment by gchickma** [comment]
@tlawrie @morarucostel Please review (and please pay particular focus to deployment-service.yaml where I have tried to accommodate the secret required for the elastic logging configuration.  Thanks.

**Comment by gchickma** [comment]
https://github.com/boomerang-io/charts/pull/49

**Comment by tlawrie** [comment]
Based on community meet up, this will be verified by @gchickma

**Comment by tlawrie** [comment]
Hey @gchickma @morarucostel does this also require a documentation update for 3.6.1?

**Comment by timrbula** [comment]
Closed by https://github.com/boomerang-io/charts/pull/58
