### ISSUE TITLE
Update the documentation with the changes required for "Redesign the eventing library to support multiple Streams and Consumers"

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/roadmap#300]
Hey @corcoja , can you please take a look and update the necessary documentation part of the changes done in #255 ?
You can create a new branch from `useboomerang.io` repo for this change.

**Comment by corcoja** [comment]
Hey @morarucostel! Do you want me to update the `boomerang-io/lib.eventing` repo docs, the documentation on [useboomerang.io](https://www.useboomerang.io) website or both?

**Comment by morarucostel** [comment]
Hey @corcoja , I believe both of them should be updated to reflect the latest. 
The action with higher priority, imo is the useboomerang.io one.
