### ISSUE TITLE
Update the documentation with the changes required for "Update SendEmailWithPostmarkTemplate to accept Message Stream"

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/roadmap#301]
Hey @tlawrie , can you please take a look and update the necessary documentation part of the changes done in #291  ?

The reason I opened the issue against roadmap, instead of useboomerang.io was to be able to reference the issues against which the work was done. Is that OK or should it be against the useboomerang.io ?

**Comment by tlawrie** [comment]
@morarucostel PR created against the documentation repository

**Comment by morarucostel** [comment]
Thank you @tlawrie for the update.
