### ISSUE TITLE
If a run once schedule is re-enabled it can be enabled with nothing to run

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#311]
### Describe the bug

Need to determine how to handle re-enabling run once schedules that were due to run in the past. Also do it from the UI?

### What project does this issue relate to?

Boomerang Flow

**Comment by tlawrie** [comment]
Upon investigation. As soon as a simple run once trigger is enabled with a trigger time in the past, it will immediately fire.

**Comment by tlawrie** [comment]
We could do a check on the execution date time and determine if its in the past.

Options are:
1. Fire it immediately post enable
2. Make it so it can never fire (which could be hard to advise the user of and then what do we do, leave it in paused? delete it? hmm)

**Comment by tlawrie** [comment]
Hey @timrbula do you have any thoughts? do we just add the text to let the user know what will happen.

**Comment by tlawrie** [comment]
The decision is to stop it from firing and move it into 'invalid' / 'error' status.

**Comment by timrbula** [comment]
@tlawrie Can you remind me on what if anything I need to do on the UI for this?

**Comment by tlawrie** [comment]
I need to see how to return a schedule with an error status and then the UI needs to be able to reflect an error.

**Comment by tlawrie** [comment]
Changes pushed in tag 3.2.60 that will put a schedule in error status if its in the past. It handles checking status for various different combinations of active, inactive, trigger disabled, and date in the past for runonce.

I also fixed the creating of a schedule when the trigger is disabled.
