### ISSUE TITLE
The flow task for "Wait for Event" document link is invalid

### ISSUE THREAD

**Issue by dlsyliu** [boomerang-io/roadmap#316]
### Describe the bug

This flow task **Wait for Event** have a problem can't view its external doc link
https://servicesessentials.ibm.com/docs/boomerang-flow/architecture/eventing-architectur
![error](https://user-images.githubusercontent.com/22931829/150054211-b1e2ab6a-53c1-487a-812a-0be261c49ec0.png)

<img width="694" alt="Wait For Event doc link" src="https://user-images.githubusercontent.com/22931829/150054129-73e4042b-66da-43e3-af3e-1fb216c4edb4.PNG">

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

1. Edit "Wait for Event" flow task
2. click on the [View Wait for Event documentation](https://servicesessentials.ibm.com/docs/boomerang-flow/architecture/eventing-architecture)

### Environment

Prod env

**Comment by tlawrie** [comment]
Thanks @dlsyliu it looks like we need to update that to point to https://www.useboomerang.io/docs/boomerang-flow/architecture/eventing

**Comment by tlawrie** [comment]
Based on community meet up, this will be updated by @timrbula. There is no internal vs public documentation it is all in the public domain. There is also no mode as these have moved to feature flags
