### ISSUE TITLE
Fix Insights API to match other filter endpoints (Actions/Schedules/Activity) and upgrade React Graph Library version

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#321]
As part of trying to refactor and share common filtering functionality across the application, we need to upgrade the Insights page to cater for the filters that have been introduced over time such as Scope and Trigger. As well as allowing multi select.

This issue is a precursor to https://github.com/boomerang-io/roadmap/issues/111 for the broader Insights update

**Comment by tlawrie** [comment]
**Updated Endpoint**

  @GetMapping(value = "/insights")
  ```
  public InsightsSummary getInsights(
      @RequestParam(defaultValue = "ASC") Optional<Direction> order,
      @RequestParam Optional<List<String>> scopes, 
      @RequestParam Optional<String> sort,
      @RequestParam Optional<List<String>> workflowIds,
      @RequestParam Optional<List<String>> teamIds, 
      @RequestParam(defaultValue = "0") int page,
      @RequestParam(defaultValue = "2147483647") int size, 
      @RequestParam Optional<Long> fromDate,
      @RequestParam Optional<Long> toDate, 
      @RequestParam Optional<List<String>> statuses,
      @RequestParam Optional<List<String>> triggers
      ```

**Comment by tlawrie** [comment]
We can still leave the fromDate and toDate as selected months.

**Comment by tlawrie** [comment]
Upgrade the carbon charts to the latest version as part of this for a first step

**Comment by tlawrie** [comment]
Hey @BenjaminRuby @LucasGrimauth @Okisa @timrbula it'd be great if we could get the minor update to the Insights page to use the new URL and have the extra filters to match all the other pages.

This will allow us to merge in a bunch of changes, including security updates that would be beneficial to @amhudson

**Comment by tlawrie** [comment]
The backend has been merged in backwards compatable.

However would still be great if the UI could be updated to match the other screens. The API will support the additional query parameters.

**Comment by timrbula** [comment]
@timrbula do what @tlawrie asks above

**Comment by timrbula** [comment]
@timrbula  Create a corresponding UI task for the above work

**Comment by timrbula** [comment]
https://github.com/boomerang-io/flow.client.web/issues/135
