### ISSUE TITLE
Workspace Creation incorrectly references Workflow instead of Activity

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#323]
The Create Workflow is checking only for is Storage Enabled and then only looking at the Activity Workspace. however then in the createworkspace its looking up the settings for the Workflow Workspace. So that doesn't match

![image](https://user-images.githubusercontent.com/16438811/150871102-ff5395a1-4da8-4f43-87f4-640ecdf5a27e.png)
![image](https://user-images.githubusercontent.com/16438811/150871121-91972434-cdfe-4bca-9286-14741ebd32c6.png)

**Comment by amhudson** [comment]
https://github.com/boomerang-io/flow.service.workflow/pull/147
