### ISSUE TITLE
The Essential launchpad team name changed not sync to flow

### ISSUE THREAD

**Issue by dlsyliu** [boomerang-io/roadmap#325]
### Describe the bug

I changed my team properties, i found after i changed the team name, it not sync to the **adminster ->Quotas** team name, there still display my previous team name.
![My old team name](https://user-images.githubusercontent.com/22931829/150899274-ba445956-5348-4b95-a3fb-9c2a3eace1fa.png)
![Admin-Quotas](https://user-images.githubusercontent.com/22931829/150899288-6467c4c8-0f4e-4697-8161-a0a7279786b0.png)
My new team name have been changed as below:
![My new team name](https://user-images.githubusercontent.com/22931829/150899351-d24f2c32-fa72-4b63-86e2-7d3ca2023dec.png)

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

1. Go to flow home page https://servicesessentials.ibm.com/flow/apps/flow/workflows
2. Click on the left navigation
3. **adminster ->Quotas** 
4. Searching the team name from teams search bar will display my old team name.

### Environment

prod env

**Comment by tlawrie** [comment]
Hi @dlsyliu thanks for this. It seems to be a very specific IBM issue. @marcusdroy @BenjaminRuby do you have any comments on this?

**Comment by marcusdroy** [comment]
Once essentials has created the flow team via internal apis there is currently no synchronization method to subscribe to team name updates

**Comment by tlawrie** [comment]
This should be resolved by https://github.com/boomerang-io/roadmap/issues/155

@gchickma @timrbula to confirm.

**Comment by timrbula** [comment]
@tlawrie Sorry don't follow here. Does this perform synchronization with team updates?

**Comment by tlawrie** [comment]
No, that's my mistake, thought it was the CICD header name not coming through.

**Comment by tlawrie** [comment]
Back to @gchickma

**Comment by tlawrie** [comment]
This won't be a problem in Flow v4 as Teams are created and managed via an API and not sync'd. Only users are sync'd.
