### ISSUE TITLE
Create a task to provide the capability to query db instances

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/roadmap#329]
**Is your request related to a problem? Please describe.**
The business needs an easy way to access data from a mongodb instance in order to perform additional analysis. 

**Describe the solution you'd like**
A workflow task capable of connecting to a mongodb instance and run a query. 
The output of the query must be accessible as a file at the end of the task execution. 

**Describe the benefits or justification for this request**
Increases the capability of the platform and opens the door to access the data without any prior transformation, allowing the transformation to be done post retrieval, in the flow.

**Additional context**
NA

**Comment by tlawrie** [comment]
Hey @morarucostel thanks for the issue. Its not currently tagged to a release but do see it included in a loader change 

https://github.com/boomerang-io/flow.loader/pull/67/files#diff-c85a304c1ca5ffe621b41e6cde3f9667226cc680991cc29115518fe5edb393e5

Should this have been reviewed before being included in the same loader change as the HTTP Task Template changes?

**Comment by tlawrie** [comment]
cc: @morarucostel @amhudson

**Comment by morarucostel** [comment]
Hey @tlawrie , yes, it should have been reviewed before being included. That is my fault, I jumped the gun there.
We can either revert it or review it part of this issue. 
The task is using the `mongosh` image from mongodb and the UI is configured like this:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/13904499/152500718-15e9facb-e611-4ce1-9f6c-4666819c9402.png">
<img width="620" alt="image" src="https://user-images.githubusercontent.com/13904499/152500846-29091763-a518-43b4-b65c-584a7f43a710.png">

**Comment by tlawrie** [comment]
Hi @morarucostel this is a good addition. Its great new tasks are being generated. Not a problem, we should probably devise a process for new tasks and a +1 or +2. We havent really ever had a process for it.

W.r.t to this task, few comments
1. If it's using an external image, we might need to document that. Im thinking we either add a list of dependent images in the architecture documentation OR add an extra column to the tasks. I think it might be better in the architecture, to add images that we depend on for tasks.
2. How does this task work for TLS required MongoDBs? 
3. Some more helper text or placeholders might be good. In the query it could have an 
> e.g. example query

**Comment by morarucostel** [comment]
@tlawrie points 2 and 3 are solved (attached as images below)
Regarding point 1, documenting the dependent images, do you think we can stick them in 3.6.1 release docs?

<img width="584" alt="image" src="https://user-images.githubusercontent.com/13904499/152532718-b45215df-bcd8-45a2-8230-a8c2140f3978.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/13904499/152532752-3b45e642-3d3e-4f48-8cc2-b72648815e2a.png">

**Comment by morarucostel** [comment]
@tlawrie also exposed, as configurable, the auth method so now the task can be used to connect to both internal in k8s hosted mongodb instance as well as external Azure hosted instance. 
The current configuration is:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/13904499/153199851-f9636f06-5716-4431-9174-988302b589c8.png">
<img width="567" alt="image" src="https://user-images.githubusercontent.com/13904499/153199914-b5723e55-ed90-4886-a555-89090b485846.png">
<img width="561" alt="image" src="https://user-images.githubusercontent.com/13904499/153199953-77814bef-1c60-4277-bec5-420f303accc5.png">

**Comment by morarucostel** [comment]
@tlawrie also updated the Architecture - Application - Components documentation with the dependency on the MongoDB shell docker image. It made sense to add the information under the already existing external dependency column of the TaskWorker.

**Comment by morarucostel** [comment]
Is it OK to map the task against 3.6.1 version?
The task template and documentation are already done.
