### ISSUE TITLE
Slack File Upload Enhancement

### ISSUE THREAD

**Issue by BenjaminRuby** [boomerang-io/roadmap#33]
## Change
**Overview**
As a user, I want to be able to supply a file path and have that file uploaded as part of a slack message. 

**Technical Detail**
the slack API provides two methods for this. Our task currently only supports an upload via a POST variable. The request is to support supplying a file Path and then the worker opening up this file and attaching as part of the API call as `file`.

For further information, reference the underlying API from slack: https://api.slack.com/methods/files.upload

**Comment by tlawrie** [comment]
Hey @BenjaminRuby @TheSaltFactory can we verify this works in the 3.1.0 release?
