### ISSUE TITLE
Flow services log level is set to debug by default

### ISSUE THREAD

**Issue by aiciobanu** [boomerang-io/roadmap#332]
### Describe the bug

When installing Flow's Helm chart using the option `general.enable.debug=false`, the logs are still set on debug.

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

 - Deploy Flow's Helm chart using the option `general.enable.debug=false`
 - Retrieve the logs

**Comment by tlawrie** [comment]
Partly solved with https://github.com/boomerang-io/flow.service.workflow/compare/fix-334-RunScheduledJobNPE?expand=1

More to come
