### ISSUE TITLE
Scheduled Job Fields mismatch

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#335]
Either on the Create or the Edit / Update fields of the scheduled job, if you have a parameter called 'name' it seems to get mapped to the name of the scheduled job.

**Comment by tlawrie** [comment]
![image](https://user-images.githubusercontent.com/16438811/160983693-b2572880-8c68-4c7c-9a84-0801f76bd82e.png)

It loads up correctly after creation (via the Run Scheduled Workflow) but as soon as you hit edit the name parameter shows up in the name of the schedule and upon save, it updates the name.

If you adjust the name field, it shows up in the name parameter and is saved.

**Comment by timrbula** [comment]
not a component library issue. This affects all parameters that have a key that matches a field in the create and edit Schedule forms. I had intended to find a solution for duplicated keys but never came back to it.
