### ISSUE TITLE
Update to spring boot 2.6.6

### ISSUE THREAD

**Issue by amhudson** [boomerang-io/roadmap#337]
Update to spring boot 2.6.6  for workflow, controller, and listener services.

**Comment by amhudson** [comment]
flow.service.workflow already updated

**Comment by tlawrie** [comment]
Also @amhudson do the other libraries need to be updated too? This is what was done for Workflow

**Upgraded**
- Spring Boot
- log4j2
- jackson-databind
- mongo-java-driver
- commons-compress
- opentracing-spring-jaeger-web-starter
- jaegr-core

**Migrated**
- springfox-swagger to sprindoc.
- Tests to JUnit5

**Cleaned** 
- the pom.xml

**Comment by timrbula** [comment]
@amhudson To continue with further updates

**Comment by amhudson** [comment]
To be addressed with https://github.com/boomerang-io/roadmap/issues/339
