### ISSUE TITLE
Fix security vulnerabilities

### ISSUE THREAD

**Issue by timrbula** [boomerang-io/roadmap#339]
## Description
Brief summary of what this Epic is, whether it's a larger project, goal, or user story. Describe the job to be done, which persona this Epic is mainly for, or if more multiple, break it down by user and job story.

## Impacts
Describe the functionality impacted and changes from this Epic

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Open Questions
What technical or functional questions are needing to be answered to achieve this Epic

## Acceptance criteria and scope
Define what is a must-have for launch and in-scope. 

| Feature | Given | When | Then |
| --- | --- | --- | --- |
| | | |

**Comment by amhudson** [comment]
@morarucostel FYI https://github.com/boomerang-io/flow.service.workflow/pull/180
