### ISSUE TITLE
HTTP Task Failure upon error status code

### ISSUE THREAD

**Issue by BenjaminRuby** [boomerang-io/roadmap#34]
**Describe the bug**
As a user of the flow HTTP task, I would expect that a task would fail if the service returns  a 5xx status code.

**To Reproduce**
Run a task and make an http request that will return in a 5xx response code. The task will still succeed 

**Expected behavior**
Expected the task to have failed.

**Additional context**
Raised by Luis - situation where they want to apply different logic if for example, "a tenant already exists"

**Comment by tlawrie** [comment]
Hey @morarucostel could you investigate this one to see what would need to change? For now, this is an investigation only to see the detailed technical design of what would need to change.

**Comment by morarucostel** [comment]
I think the design of the HTTP Task should follow these lines:
- It should **NOT** fail the task based on the http status code. Doing that it encapsulates logic into the Task, logic that will limit the user's ability to model the workflow.
- The HTTP task should set as output parameter the http response code. Then the flow logic can be desinged based on a switch with a regex of a response code, allowing fallbacks, retries with sleep or anther path to the flow.
- Also the response Headers should be available as output parameters, to increase the ussage of the flow
- The HTTP Task should allow for the non JSON response to get received and returned (currently it is doing a `response = JSON.parse(output)` and thus forces the output to be a JSON, even a valid HTML will fail the task),
- The Task should allow both HTTP and HTTPS calls (currently it allows just https - fails when provided an http address),

**Comment by morarucostel** [comment]
Hey @tlawrie , what do you think?
Should I take a stab at it and try to implement the points from above?

**Comment by tlawrie** [comment]
Hi @morarucostel so we have the concept of a link state i.e. the always, on success, on failure that can be attributed to whats next. That was built for this exact purpose around what is a 'failure'.

So could we not follow the logic that 4xx and 5xx are failures? 
> 4xx client error – the request contains bad syntax or cannot be fulfilled
> 5xx server error – the server failed to fulfil an apparently valid request

Regarding the points you make above, they are also valid
1. On error, IF we don't agree that errors should result in error path (which i think a strong argument could be made for) then we could have a drop down in the task itself for specifying code range of success? i.e. do I expect a 200 or a 400 or what now.
2. Agree. Response code should be an output parameter
3. Im not sure what you mean by response headers but again, more output parameters the better in this case
4. Should the task ask what the response is?
5. Agreed. HTTP and HTTPS should be supported. again it can programmatically figure it out or we can ask the user on the task.

**Comment by tlawrie** [comment]
hey @morarucostel is this now closed via #45 as well?

**Comment by morarucostel** [comment]
hey @tlawrie , not sure about the #45 , actually this one is closed by 
this one is now closed via https://github.com/boomerang-io/worker.flow/pull/45

**Comment by tlawrie** [comment]
Thanks for confirming. Closing issue.
