### ISSUE TITLE
Manual Approval task is missing the specifics on the configuration page

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/roadmap#341]
### Describe the bug

Trying to use the `Manual Approval` task in a workflow, doesn't allow the end-user to configure its specifics, like the question being asked.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/13904499/167218722-18e45f68-232a-4cc7-a168-81c1ec068c20.png">

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

* create a workflow
* drag&drop the `Manual Approval` task
* edit the task

### Environment

* Browser: Firefox 
* Flow version: 3.8.0

**Comment by timrbula** [comment]
@amhudson @tlawrie 

This is not a front-end bug. The response coming from the service has an empty config array that determines what is rendered in the "specifics" section

**Comment by timrbula** [comment]
Closed w/ a short term solution. Need to open up something larger around approvals for all scopes.
