### ISSUE TITLE
Inconsistent parallel execution results for File JSONPath to Parameter task

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/roadmap#342]
### Describe the bug

Running in parallel multiple `File JSONPath to Parameter` tasks, which reads from the same file but different properties e.g. property a and property b, sometimes (not always) the following task will get only the value of a or the value of b when referencing both the $(tasks.task1.results.evaluation) and $(tasks.task2.results.evaluation).

<img width="926" alt="image" src="https://user-images.githubusercontent.com/13904499/167219453-ca630f0e-3614-4a6b-8a58-6d7ff9598786.png">

As an example, in the workflow depicted above, in the `Destroying the planet` task, the instructions are configured like (showing the two evaluations from the previous ran in parallel 2 tasks): 
```
First "File JSONPath to Parameter" picked-up value is: "$(tasks.Find Resistance leader.results.evaluation)"
Second "File JSONPath to Parameter" picked-up value is: "$(tasks.Find Resistance troops.results.evaluation)"
```

When executing the workflow (its not happening always but rather with a 80% incident rate), you will notice that actually the `Destroying the planet` task will show in its rendered instructions the same picked-up value, either from task `Find Resistance leader` or from task `Find Resistance troops` even though the results evaluation of those two are always different, since they are taking different values from a JSON.

As an example, running the above flow, 
**sometimes the `Destroying the plane` task shows this:**

<img width="605" alt="image" src="https://user-images.githubusercontent.com/13904499/167221537-22179c5b-32c7-47d1-b3c6-c5834f2a3150.png">

**and some other times it shows this:**

<img width="567" alt="image" src="https://user-images.githubusercontent.com/13904499/167223503-deda17cc-a4e9-40a8-8c56-14921606f5fe.png">

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

Already described above.

### Environment

Flow: 3.8.0

**Comment by tlawrie** [comment]
Might need to get @amhudson or @marcusdroy involved to deep dive.

Can you check if the result parameter is right on the Tekton task? If so then it might just be a mix up in the code for saving it or retrieving it at runtime.

**Comment by amhudson** [comment]
I've been able to replicate but have not found the cause yet. Continuing to investigate...

**Comment by amhudson** [comment]
Continuing to investigate. Requests from workflow look ok. However when the incorrect parameter is returned, I believe. something is going on with controller.
