### ISSUE TITLE
Manual Task fails to execute the 2 actions, Complete Successfully and Unsuccessfully

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/roadmap#343]
### Describe the bug

Adding a `Manual Task` in a workflow, when it is executed, it fails when taking any of both actions: 

When either option is selected, `Complete Successfully` or `Complete Unsuccessfully`, it quickly shows the image below, then reloads the page and brings you back to the workflow.

![image](https://user-images.githubusercontent.com/13904499/167223954-12c20a3e-87b8-4290-bfc3-bf2fb36e6c9f.png)

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

Described above

### Environment

Flow: 3.8.0
Browser: Firefox

**Comment by timrbula** [comment]
@BenjaminRuby Do you or someone else on the team have any cycles to look at this?

**Comment by tlawrie** [comment]
@morarucostel I tried to reproduce this using the latest webapp and workflow service tags, and I couldn't get it to occur.

Could you retry?

**Comment by tlawrie** [comment]
Resolved as working in 3.10.0
