### ISSUE TITLE
Quota UI dialog doesn't show the input text with the value

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/roadmap#348]
### Describe the bug

Editing any of the quota values, shows the input text without the value, making it hard to update the value. It only shows the plus and minus buttons without the value.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/13904499/167367667-0d00ac80-3061-4d71-a5f7-8ddc6df55d61.png">

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

* Hamburger menu -> Team Quotas
* Edit any quota

### Environment

Flow: 3.8.0
Browser: Chrome and FF

**Comment by tlawrie** [comment]
Hey @morarucostel should these bugs be tagged to a Release? or be fixed prior to 3.9.0 close out?
