### ISSUE TITLE
Importing workflow into "My Workflows" area doesn't import the workflow

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/roadmap#351]
### Describe the bug

Importing a workflow into the "My Workflows" area shows in the UI's notifications area that the import was successfully, however you can not see the imported workflow in the "My Workflows" page. 

The workflow is being saved in the database however is missing the "ownerUserId" key, and for that reason it is not loaded up in the "My Workflows" page. 

There is no setOwnerUserId in the
 https://github.com/boomerang-io/flow.service.workflow/blob/e9eefde2448bfa17da9cbf87281d0c61570ee4e1/src/main/java/io/boomerang/service/crud/WorkflowServiceImpl.java#L547

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

Import a new workflow in the My Workflow area.

### Environment

* Browser: Any
* Flow: 3.8.0

**Comment by amhudson** [comment]
@morarucostel We do record the `OwnerUserId` [here](https://github.com/boomerang-io/flow.service.workflow/blob/e9eefde2448bfa17da9cbf87281d0c61570ee4e1/src/main/java/io/boomerang/service/crud/WorkflowServiceImpl.java#L517). I'm not able to replicate. Can you give me the workflow you are trying to import?
