### ISSUE TITLE
Additional Setting needed for Slack Signing Secret

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#360]
An additional Setting is needed as part of the extensions configuration for the Slack signing secret

```json
        {
            "description" : "The Signing Secret from your Slack apps credentials.",
            "key" : "slack.signingSecret",
            "label" : "Slack Signing Secret",
            "type" : "secured",
            "value" : "",
            "readOnly" : false
        }
```

Loader to be updated with additional item.

**Comment by tlawrie** [comment]
Hey @gchickma are you able to do the loader update?

**Comment by dlandry318** [comment]
Hey @tlawrie, what config will this new setting be under? e.g. Task Config, Workspace Config, etc

**Comment by tlawrie** [comment]
hi @dlandry318  thanks for looking into this. Its part of the Extensions Configuration.
