### ISSUE TITLE
Ability to see a detailed kubernetes information 

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#38]
**Is your request related to a problem? Please describe.**
For an activity it would be useful for users that are managing Flow instances and workflows, to be able to see the kubernetes label information to be able to run kubectl commands such as `kubectl get pod -l <labels>`.

**Describe the solution you'd like**
This could be implemented as a modal on the Activity Detail page with the labels and a copy button

**Describe the benefits or justification for this request**
Users that are managing instances and wanting to find the particular pods will find this information extremely handy. Probably only operators if that role was implemented.

**Additional context**
FYI: @simon-harris-ibm

**Comment by tlawrie** [comment]
Implement a workflow detail icon next to the workflow name that opens a modal to display advanced detailed information. This includes some information that's on the ribbon already but also information for the labels that are present on a workflow.

There is a similar implementation on the Task Manager screen.

**Details to be included**
Labels:
- a visual display of labels color view key=value bubble. Its the display part of the creatable.
- detailed kube read only input box label string of key=value,key=value,key=value with a copy button or action button

**Comment by BenjaminRuby** [comment]
@marcusdroy @tlawrie where are we pulling the kube info from?

**Comment by tlawrie** [comment]
There are always default labels of
- `boomerang.io/workflow-id`
- `boomerang.io/activity-id`
- `boomerang.io/product` _potentially_

plus
- custom labels

**Comment by BenjaminRuby** [comment]
Hey @LucasGrimauth could you get started on this task?

we want to launch a modal on the execution screen similar as to the approach in task manager for displaying history. Right next to where the workflow name is displayed

**within the modal**: display the label key:value pairs using the bubbles from the createable component - and then show a code copy section for the kubernetes command to get the pods with those labels.

The workflows summary endpoint will have the custom labels information: labels array.

Then for the two default labels listed in the story, the keys are listed above: `boomerang.io/workflow-id`, `boomerang.io/workflow-activity-id` - the value would be the workflowId and the activityId

**Comment by tlawrie** [comment]
@Okisa @BenjaminRuby small change. The label for the activity-id is now workflow-activity-id
