### ISSUE TITLE
Task Input Parameter Read Only not being identified

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#45]
**Describe the bug**
When a task input parameter is marked read only from the UI, it is not identifying as read only on the task input modal nor does it show the default value that would be there.

**To Reproduce**

- Set task input parameter to read only in the task manager
- Navigate to a workflow and edit the task
- Readonly field does not identify as read only nor does it show the default value

**Expected behavior**
Clearly defined as read only and a value displayed

**Screenshots**
n/a

**Additional context**

**Comment by Okisa** [comment]
Pushed a fix to this PR related to task template keys. https://github.com/boomerang-io/flow.client.web/pull/22
Now the read only input shows the default value.
