### ISSUE TITLE
Version Upgrade Toggle Modal Layout

### ISSUE THREAD

**Issue by BenjaminRuby** [boomerang-io/roadmap#54]
I would expect that the toggle would be displayed on the right-hand upgrade side in the same manner as it is displayed on the left.

![image (16).png](https://images.zenhubusercontent.com/5f997c3d144cc0adc7d23276/bf12cf97-c9a5-4162-84ad-dc10856c15cd)

**Comment by Okisa** [comment]
Opened a PR for this bug here:
https://github.com/boomerang-io/flow.client.web/pull/26

**Comment by tlawrie** [comment]
@BenjaminRuby did this get merged into the latest update?
