### ISSUE TITLE
[Epic] Flow Verified Task Cleanup and Verifications

### ISSUE THREAD

**Issue by BenjaminRuby** [boomerang-io/roadmap#6]
With the move to open source, we will now have new collaborators contributing their own tasks. The tasks that our team officially supports now have the distinction of being "verified". With this new distinction, I would like to make sure that all our tasks are:
1.   Properly functioning without any bugs
2.  Filled with appropriate helper text, required fields, detailed logging 

As part of these changes, you will potentially be contributing to our flow.worker code-base. If you find a bug within the function being run by the task, you can create a branch off of main with a proposed fix. Also you are able to add additional logging statements with your pull request. 

For tasks that need to be given more clear helper/informative text. This is a change to the task template. You can make those changes via the Task Manager feature in our web app within our dev environment. Create a new version with the proposed changes and I will review as part of the acceptance criteria. 

If you are setting up an SSH key for GitHub on your computer for the first time, here is a good source for getting started: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by tlawrie** [comment]
Switched to @morarucostel based on the work that has been completed so far in this area. Will keep open to track how to close out a standard result parameter for all the verified tasks.
