### ISSUE TITLE
Set Output Property System Task does not match new Syntax

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#63]
**Describe the bug**
The Set Output Property System Task does not match new Syntax and should be called Set Result Parameter

**To Reproduce**

- Navigate to the Workflows Editor and look at the Task Pallette

**Expected behavior**
Would expect to see a Set Result Parameter task

**Additional context**

- We also need to update the task description that's shown

**Comment by tlawrie** [comment]
Hi @amhudson ready for a loader update.

**Comment by amhudson** [comment]
https://github.com/boomerang-io/flow.loader/pull/21
