### ISSUE TITLE
Read File To Property file utilities task is incorrectly named

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#64]
**Describe the bug**
Read File To Property file utilities task is incorrectly named. The new syntax should be Read File To Parameter.

**To Reproduce**

- Navigate to the Workflows Editor and look in the Task Pallette under File Utilities

**Additional context**
Need to double check the tasks description too.

**Comment by tlawrie** [comment]
Hi @amhudson ready for a loader update.

**Comment by amhudson** [comment]
https://github.com/boomerang-io/flow.loader/pull/21
