### ISSUE TITLE
Result Parameters are not documented for the tasks

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#65]
**Describe the bug**
In the task documentation there is a column for result parameters that a task may provide. None are documented, however it is known that some tasks do create result parameters such as the HTTP Task.

**Expected behavior**
A clear list of all the result parameters.

**Additional context**
The exercise of documenting result parameters also provides the right moment to identify tasks that **should** have result parameters

**Comment by tlawrie** [comment]
We also need to define all the result parameters on the task template

**Comment by morarucostel** [comment]
@tlawrie We have a couple of missed documented task's output. 

I'll push a pr wih the changes to the docs. 
I don't see any reason why we wouldn't push it against the current 3.2 version. What do you think?

**Comment by morarucostel** [comment]
These are the missing documented result parameters

**File Utilities**
readFileToProperty - maps a file to a property, the key being the task configured property key
readPropertiesFromFile - a list of properties based on the provided file
replaceTokensInFile - "files" the list of files where the replace was applied

**ServiceNow**
getIncidents - "incidents" list of incidents matching the search criteria

**Utilities**
Execute HTTP Call - "response" the response content of the http call
jsonPathToProperty - the configured property key containing the corresponding JSON query path

**Comment by tlawrie** [comment]
Good pick up.

W.r.t to the update, we have already branched for `flow-release-3.3` so its easier to just update for it. Otherwise if you want it also in 3.2 you can do two separate PRs but its probably not necessary.

**Comment by tlawrie** [comment]
@morarucostel have we updated the task lists in the 3.3 documentation for all the new / updated / removed tasks?

**Comment by morarucostel** [comment]
@tlawrie Yes, there are in the updated documentation draft PR for 3.3
