### ISSUE TITLE
Oops looks like there is an issue

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#69]
**Describe the bug**
The current Archive Task Template button shows a confirmation model with incorrect information on how to contact for full deletion.

**To Reproduce**
Navigate to Task Manager > Select a Task > Click Archive in top right.

**Expected behavior**
No mention on the confirmation modal of support

**Comment by Okisa** [comment]
Pushed a tag to dev.
[This PR](https://github.com/boomerang-io/flow.client.web/pull/24) contains the fix for this bug.
