### ISSUE TITLE
View task activity by clicking on Activity Flow Node

### ISSUE THREAD

**Issue by marcusdroy** [boomerang-io/roadmap#73]
**Describe the solution you'd like**

View task activity by clicking on Activity Flow Node.

**Describe the benefits or justification for this request**

When viewing a large amount of tasks with branching paths on activity viewer, it would be good to view the task detail by clicking on the graph to get access to logs easier.

**Comment by BenjaminRuby** [comment]
@LucasGrimauth could you have a look at this one tomorrow? It may not be easy to implement since the graph is rendered by a library... but perhaps there is something we can do to transfer the focus to the task log item in the side panel when the corresponding node is clicked
