### ISSUE TITLE
Rename Set Output Properties

### ISSUE THREAD

**Issue by BenjaminRuby** [boomerang-io/roadmap#74]
**Describe the bug**
On the execution screen. We currently have a button to display "set output properties" that language needs to be changed to "set result parameters" per our updated language throughout the application.

**Comment by Okisa** [comment]
@BenjaminRuby I didn't find this button. As I could see, the Set Output Properties is a task and seems to be already been renamed to Set Result Parameters.

**Comment by tlawrie** [comment]
Hey @Okisa I believe this button is a shadow button located on the Workflow Activity Detail page and only shows up when there a result parameters set as part of the workflow.

**Comment by Okisa** [comment]
![image.png](https://images.zenhubusercontent.com/5fdb5cec3fe13a19b650e279/32ca3045-8e4f-410e-bae3-d651d8561de9)

This was the only place I found the text a bit different, so I updated from `Output` to `Result`.

![image.png](https://images.zenhubusercontent.com/5fdb5cec3fe13a19b650e279/d0dfce1e-7a65-42e4-b113-812d258578c4)
Still not able to find the button in the workflow activity detail, even if we have a result parameters set.

**Comment by tlawrie** [comment]
Thanks @Okisa i think this can be moved to verify as part of release
