### ISSUE TITLE
Task Categories displayed in 3 different ways

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#85]
**Describe the bug**
On the task template screen there is a section for Category that is as entered by the user i.e. I ended `Communication with Slack` however at the top of the screen it also has the category and its been adjusted to `Communication with slack` (lowercase s) and then also on the Designer it made it upper case on each word `Communication With Slack`. 

**To Reproduce**

- Navigate to the Task Manager screen OR
- Navigate to the Designer screen and look at the pallete

**Expected behavior**

Would expect it to be as entered by the user in all locations.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f96002d49baed1deae1cb62/87d830e3-cc34-4c41-b942-2c4eaba5807c)
![image.png](https://images.zenhubusercontent.com/5f96002d49baed1deae1cb62/5302ec51-fe03-46bb-a790-7d4c7e624b32)
![image.png](https://images.zenhubusercontent.com/5f96002d49baed1deae1cb62/d2c5b60e-e11c-4638-9e45-efbd2730ec1a)

**Comment by Okisa** [comment]
Tag 3.0.97 is in dev and have a fix for this.
Also, opened a PR: https://github.com/boomerang-io/flow.client.web/pull/35
