### ISSUE TITLE
DAKS error when clicking profile in standalone mode

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#86]
**Describe the bug**
Upon clicking on the profile in the top right a DAKS error occurs.

**To Reproduce**

1. Navigate to workflows
2. Click on the profile in the top right of nav bar

**Expected behavior**
You can see the expanded profile menu

**Comment by tlawrie** [comment]
Hi @Okisa, I think you were able to fix this?

**Comment by Okisa** [comment]
Yep. Tag 3.0.96 has this fix.
PR related to this fix: https://github.com/boomerang-io/flow.client.web/pull/33
