### ISSUE TITLE
Flow Activity Date Range Selection

### ISSUE THREAD

**Issue by BenjaminRuby** [boomerang-io/roadmap#87]
**Describe the bug**
This is on Flow activity table.

Try entering a start date and end date and the component is behaving a bit erratically. On first try, the start date is not saved in the input segment of the component. 

**To Reproduce**
Steps to reproduce the behavior. Think about:

**Expected behavior**
After selecting dates via dropdown, they are displayed on the inputs for start and end date. Then the request is made to get the data for that date range. 

**Screenshots**
![Screen Shot 2021-04-01 at 9.49.58 AM.png](https://images.zenhubusercontent.com/5f997c3d144cc0adc7d23276/5db951df-bdcd-44df-978a-cbe2771aa52f)

**Environment (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 89.0.4389.90

**Comment by tlawrie** [comment]
@BenjaminRuby was this resolved and in 3.2?
