### ISSUE TITLE
Updated Icons for Workflows

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#99]
**Is your request related to a problem? Please describe.**
Workflows currently have a very limited subset of icons that can be set.

**Describe the solution you'd like**
Introduced better icons for Workflows from Carbon with a greater range and description of what they mean. Similar to the clear distinctions for Tasks.

**Describe the benefits or justification for this request**
A clear and concise list of benefits for this change

**Additional context**

**Comment by tlawrie** [comment]
Hey @LucasGrimauth what new icons did we choose? can you take a screenshot? how are the icon names linked i.e. did we just add additional? did we deprecate any and if we did, what will workflows that referenced that icon use?

**Comment by BenjaminRuby** [comment]
Hey @tlawrie it looks like Lucas did not deprecate any Icons, but did add a good bit more from Carbon. It looks good to me so I am going to merge in.

**Comment by tlawrie** [comment]
@BenjaminRuby is making an update to the default icon choice to be the Bot... once that is up we can mark this item as verified
